---
  - name: CONFIGURE SINGLE AREA OSPF
    hosts: routers
    gather_facts: false
    connection: local
    vars:
      cli:
        username: cisco
        password: cisco123!

    tasks:
      - name: CONFIGURE OSPF FOR RAFAELA
        when: ansible_host == "192.168.2.1"
        ios_config:
          provider: "{{ cli }}"
          parents: router ospf 100
          lines:
            - network 10.0.0.4 0.0.0.3 area 0
            - network 192.168.2.0 0.0.0.255 area 0
            - passive-interface FastEthernet0/1

      - name: CONFIGURE OSPF FOR GREENLAND
        when: ansible_host == "192.168.1.1"
        ios_config:
          provider: "{{ cli }}"
          parents: router ospf 100
          lines:
            - network 10.0.0.0 0.0.0.3 area 0
            - network 192.168.1.0 0.0.0.255 area 0
            - passive-interface FastEthernet0/1

      - name: CONFIGURE OSPF FOR MONCARLO
        when: ansible_host == "10.0.0.2"
        ios_config:
          provider: "{{ cli }}"
          parents: router ospf 100
          lines:
            - network 10.0.0.0 0.0.0.3 area 0
            - network 10.0.0.4 0.0.0.3 area 0

      - name: SAVE THE CONFIGURATION
        ios_config:
          provider: "{{ cli }}"
          lines:
            - do write

      - name: PRINT IP ROUTES
        ios_command:
          provider: "{{ cli }}"
          commands:
            - show running-config
        register: config

      - name: SAVE OUTPUT TO ./iosconfig/ 
        copy:
          content: "{{config.stdout[0]}}"
          dest: "iosconfig/showrun{{inventory_hostname}}.txt"
